a = int(int("Enter the value of first variable: "))
b = int(input("Enter the value of second variable"))

print("Two numbers are equel nor not: " , a==b)
print('two number are not equel or not:', a!=b)
print('a is less than orquyal to b ')
print()
print()
print()
print()
print()
print()
print()
print()