a = int(input('Enter the value of first variable'))
b= int(input("Ebter value of second variable "))

print('a=b', a==b)
print('a+=b', a+b)
print('a-=b', a-b)
print('a*=b',a*b)
print('a%=b:', a%b)
print('a**=b', a**b)
print('a//=b', a//b)
